[general]
static=yes
writeprotect=no

[support-incoming]
exten => 1000,1,NoOp(Incoming test extension)
 same => n,Answer()
 same => n,Stasis(support_bot)
 same => n,Hangup()

[support-test]
exten => test,1,NoOp(Local test call path)
 same => n,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()

exten => s,1,NoOp(ARI originated call default)
 same => n,Answer()
 same => n,Stasis(support_bot)
 same => n,Hangup()
